const mongoose = require('mongoose');
require('dotenv').config();

const Platform = require('./models/Platform');
const connectDB = require('./config/db');

const platforms = [
  {
    name: 'Outlier AI',
    shortDescription: 'Train AI models by providing expert feedback and data labeling tasks.',
    fullDescription: 'Outlier AI is a cutting-edge platform that connects domain experts with AI companies needing high-quality training data. You\'ll work on tasks like evaluating AI responses, writing prompts, coding challenges, and creative writing assessments. The platform is ideal for professionals in STEM, writing, and specialized domains who want to leverage their expertise for income.',
    category: 'AI Tools',
    earningPotential: '$$$$',
    rating: 4.3,
    website: 'https://outlier.ai',
    logo: '',
    steps: [
      'Visit outlier.ai and click "Apply Now"',
      'Complete your profile with expertise details',
      'Take the qualification assessment',
      'Get approved and start receiving tasks',
      'Complete tasks and earn per hour/task',
    ],
    pros: [
      'High pay rates ($15-50/hour)',
      'Flexible schedule — work anytime',
      'Remote work from anywhere',
      'Intellectually stimulating tasks',
      'Growing demand for AI trainers',
    ],
    cons: [
      'Inconsistent task availability',
      'Strict quality requirements',
      'Some tasks can be repetitive',
      'Payment processing may take time',
    ],
    tags: ['AI', 'Machine Learning', 'Data Labeling', 'Remote', 'Expert'],
  },
  {
    name: 'Remotasks',
    shortDescription: 'Complete micro-tasks like image annotation, data collection, and AI training.',
    fullDescription: 'Remotasks is a popular micro-task platform powered by Scale AI. It offers various tasks including image and video annotation, data categorization, transcription, and AI model evaluation. The platform is beginner-friendly with built-in training courses and supports workers worldwide. Tasks range from simple categorization to complex 3D point cloud annotation for self-driving cars.',
    category: 'Micro Tasks',
    earningPotential: '$$',
    rating: 3.8,
    website: 'https://www.remotasks.com',
    logo: '',
    steps: [
      'Sign up at remotasks.com with your email',
      'Complete onboarding tutorials',
      'Pass qualification exams for task types',
      'Start working on available tasks',
      'Get paid weekly via PayPal or crypto',
    ],
    pros: [
      'No prior experience needed',
      'Free training provided',
      'Wide variety of tasks',
      'Weekly payments',
      'Global availability',
    ],
    cons: [
      'Lower pay for basic tasks',
      'Some tasks require long training',
      'Task availability varies by region',
      'Quality requirements can be strict',
    ],
    tags: ['Micro Tasks', 'Data Annotation', 'Beginner Friendly', 'Remote', 'Weekly Pay'],
  },
  {
    name: 'Clickworker',
    shortDescription: 'Earn money through surveys, writing, data categorization, and web research.',
    fullDescription: 'Clickworker is a well-established crowdsourcing platform offering diverse micro-tasks. From text creation and SEO writing to app testing and survey participation, there\'s always something to work on. The platform includes UHRS (Universal Human Relevance System) integration, providing access to Microsoft\'s task pool. It\'s ideal for those looking for flexible, easy-to-start side income.',
    category: 'Surveys',
    earningPotential: '$$',
    rating: 3.5,
    website: 'https://www.clickworker.com',
    logo: '',
    steps: [
      'Register at clickworker.com',
      'Complete your profile assessments',
      'Access UHRS for additional tasks',
      'Choose tasks that match your skills',
      'Earn and withdraw via PayPal',
    ],
    pros: [
      'Easy to get started',
      'Variety of task types',
      'UHRS access for more tasks',
      'No minimum work hours',
      'Reliable payments',
    ],
    cons: [
      'Low pay per task',
      'Income can be unpredictable',
      'Limited tasks in some regions',
      'Some assessments are difficult',
    ],
    tags: ['Surveys', 'Writing', 'UHRS', 'Flexible', 'PayPal'],
  },
  {
    name: 'Fiverr',
    shortDescription: 'Sell freelance services starting at $5 — from design to programming.',
    fullDescription: 'Fiverr is the world\'s largest marketplace for freelance services. As a seller, you create "gigs" offering services in categories like graphic design, web development, writing, video editing, voiceovers, and more. The platform handles payments, provides seller protection, and offers tools to grow your freelance business. Top-rated sellers can earn thousands per month.',
    category: 'Freelancing',
    earningPotential: '$$$$',
    rating: 4.2,
    website: 'https://www.fiverr.com',
    logo: '',
    steps: [
      'Create a Fiverr account',
      'Set up your seller profile with portfolio',
      'Create compelling gig listings',
      'Optimize with keywords and competitive pricing',
      'Deliver quality work and build reviews',
    ],
    pros: [
      'Massive global marketplace',
      'Set your own prices',
      'Build a sustainable freelance business',
      'Seller protection and support',
      'Multiple income streams possible',
    ],
    cons: [
      'Fiverr takes 20% commission',
      'Competitive marketplace',
      'Takes time to build reputation',
      'Payment held for 14 days initially',
    ],
    tags: ['Freelancing', 'Gig Economy', 'Design', 'Programming', 'Writing'],
  },
  {
    name: 'Upwork',
    shortDescription: 'Find freelance projects in development, design, writing, and business.',
    fullDescription: 'Upwork is the premier platform for professional freelancers. Unlike Fiverr\'s gig-based model, Upwork focuses on project-based and hourly contracts. Clients post jobs, and freelancers submit proposals. The platform supports long-term relationships, with many freelancers building full-time careers. Features include time tracking, milestone payments, and a robust dispute resolution system.',
    category: 'Freelancing',
    earningPotential: '$$$$$',
    rating: 4.0,
    website: 'https://www.upwork.com',
    logo: '',
    steps: [
      'Create a professional Upwork profile',
      'Take skills tests to verify expertise',
      'Browse jobs and submit tailored proposals',
      'Win contracts and deliver exceptional work',
      'Build your reputation with 5-star reviews',
    ],
    pros: [
      'High-value projects available',
      'Long-term client relationships',
      'Professional tools and tracking',
      'Escrow payment protection',
      'Career-building potential',
    ],
    cons: [
      'Service fee up to 20%',
      'Highly competitive for beginners',
      'Connects system costs money',
      'Account approval can be difficult',
    ],
    tags: ['Freelancing', 'Professional', 'Long-term', 'Development', 'Business'],
  },
  {
    name: 'Swagbucks',
    shortDescription: 'Earn rewards by taking surveys, watching videos, and shopping online.',
    fullDescription: 'Swagbucks is one of the most popular rewards platforms offering multiple ways to earn. Complete surveys, watch video content, search the web, play games, and earn cashback on online shopping. Points (called SB) can be redeemed for gift cards or PayPal cash. While individual tasks pay small amounts, consistent daily use can generate meaningful passive income.',
    category: 'Surveys',
    earningPotential: '$',
    rating: 3.7,
    website: 'https://www.swagbucks.com',
    logo: '',
    steps: [
      'Sign up at swagbucks.com (get bonus SB)',
      'Complete your profile for survey matching',
      'Start with daily polls and searches',
      'Take surveys and watch videos',
      'Redeem SB for gift cards or PayPal cash',
    ],
    pros: [
      'Multiple earning methods',
      'Low effort tasks available',
      'Welcome bonus for new users',
      'Trusted platform (BBB A+ rated)',
      'Cashback on shopping',
    ],
    cons: [
      'Low earnings per task',
      'Survey disqualifications common',
      'US-focused (limited elsewhere)',
      'Takes time to accumulate points',
    ],
    tags: ['Surveys', 'Rewards', 'Cashback', 'Passive Income', 'Gift Cards'],
  },
  {
    name: 'UserTesting',
    shortDescription: 'Get paid $10-60 per test to review websites and apps with your feedback.',
    fullDescription: 'UserTesting pays you to test websites, apps, and prototypes. You\'ll share your screen, speak your thoughts aloud, and complete tasks while being recorded. Tests typically take 15-60 minutes and pay $10 for standard tests and up to $60+ for live interviews. It\'s an excellent platform for articulate people who enjoy sharing opinions about digital products.',
    category: 'Micro Tasks',
    earningPotential: '$$$',
    rating: 4.1,
    website: 'https://www.usertesting.com',
    logo: '',
    steps: [
      'Apply at usertesting.com',
      'Complete a sample test',
      'Get approved as a tester',
      'Accept and complete available tests',
      'Get paid via PayPal within 7 days',
    ],
    pros: [
      '$10 minimum per test',
      'Live interviews pay $30-60+',
      'Tests are interesting and varied',
      'Quick PayPal payments',
      'Help improve real products',
    ],
    cons: [
      'Limited test availability',
      'Must meet demographic requirements',
      'Need a quiet testing environment',
      'Screener questions can filter you out',
    ],
    tags: ['User Testing', 'UX Research', 'Feedback', 'PayPal', 'Video'],
  },
  {
    name: 'Appen',
    shortDescription: 'Contribute to AI training through data annotation, evaluation, and linguistics.',
    fullDescription: 'Appen (formerly Figure Eight) is a global leader in AI training data. They connect over a million contributors worldwide with projects from major tech companies. Tasks include search relevance evaluation, content moderation, linguistic data collection, image/video annotation, and more. Many projects offer consistent, long-term work with set schedules.',
    category: 'Data Labeling',
    earningPotential: '$$$',
    rating: 3.6,
    website: 'https://appen.com',
    logo: '',
    steps: [
      'Create an account at appen.com',
      'Complete your profile with language and demographic info',
      'Browse and apply to available projects',
      'Complete qualification tasks',
      'Work on approved projects consistently',
    ],
    pros: [
      'Well-established company',
      'Variety of project types',
      'Some projects offer consistent hours',
      'Global availability',
      'Work with major tech brands',
    ],
    cons: [
      'Slow onboarding process',
      'Project availability varies',
      'Strict quality guidelines',
      'Payment can be slow (monthly)',
    ],
    tags: ['Data Labeling', 'AI Training', 'Linguistics', 'Search Evaluation', 'Global'],
  },
  {
    name: 'Toloka',
    shortDescription: 'Complete AI data labeling tasks from Yandex — available worldwide.',
    fullDescription: 'Toloka by Yandex is a crowdsourcing platform focused on AI data labeling and annotation. It offers tasks like image classification, text moderation, audio transcription, and search relevance evaluation. The platform features a clean interface, transparent pricing, and multiple payment options. It\'s particularly popular in developing countries due to good relative pay rates.',
    category: 'Data Labeling',
    earningPotential: '$$',
    rating: 3.4,
    website: 'https://toloka.ai',
    logo: '',
    steps: [
      'Register at toloka.ai',
      'Complete phone verification',
      'Browse training and available tasks',
      'Complete tasks accurately',
      'Withdraw earnings via PayPal, Skrill, or Payoneer',
    ],
    pros: [
      'Easy registration',
      'Many tasks available',
      'Multiple payment methods',
      'Clean, user-friendly interface',
      'Quick payments (daily minimum)',
    ],
    cons: [
      'Low pay per task',
      'Repetitive tasks',
      'Some tasks have strict accuracy requirements',
      'Limited high-paying tasks',
    ],
    tags: ['Data Labeling', 'Yandex', 'Micro Tasks', 'Global', 'Multiple Payments'],
  },
  {
    name: 'Teachable',
    shortDescription: 'Create and sell online courses on any topic you\'re expert in.',
    fullDescription: 'Teachable empowers creators to build and sell online courses. Whether you\'re an expert in cooking, coding, photography, or business, you can create professional courses with video lessons, quizzes, and certificates. The platform handles hosting, payments, and student management. Top creators earn six to seven figures annually from their course businesses.',
    category: 'Teaching',
    earningPotential: '$$$$$',
    rating: 4.4,
    website: 'https://teachable.com',
    logo: '',
    steps: [
      'Sign up for a Teachable account',
      'Plan your course curriculum',
      'Record and upload video lessons',
      'Set pricing and launch your course',
      'Market and grow your student base',
    ],
    pros: [
      'Unlimited earning potential',
      'Keep most of your revenue',
      'Professional course hosting',
      'Built-in payment processing',
      'Passive income once created',
    ],
    cons: [
      'Requires significant upfront effort',
      'You need to drive your own traffic',
      'Monthly platform fee',
      'Competitive market',
    ],
    tags: ['Teaching', 'Online Courses', 'Passive Income', 'Content Creation', 'Expert'],
  },
  {
    name: 'Midjourney',
    shortDescription: 'Create and sell AI-generated artwork, designs, and visual content.',
    fullDescription: 'Midjourney is a leading AI image generation tool that artists and designers use to create stunning visuals. While the tool itself requires a subscription, creative entrepreneurs use it to sell print-on-demand products, stock photos, social media content, book covers, and marketing materials. Combined with platforms like Etsy or Redbubble, it becomes a powerful income stream.',
    category: 'AI Tools',
    earningPotential: '$$$',
    rating: 4.5,
    website: 'https://www.midjourney.com',
    logo: '',
    steps: [
      'Subscribe to Midjourney',
      'Learn prompt engineering techniques',
      'Create unique, high-quality artwork',
      'List designs on POD platforms (Etsy, Redbubble)',
      'Market your designs and scale up',
    ],
    pros: [
      'Create professional art without art skills',
      'Unlimited creative possibilities',
      'Multiple monetization paths',
      'Growing demand for AI art',
      'Low startup cost',
    ],
    cons: [
      'Monthly subscription required',
      'Competitive market',
      'Copyright considerations',
      'Need marketing skills to succeed',
    ],
    tags: ['AI Art', 'Design', 'Print on Demand', 'Creative', 'Passive Income'],
  },
  {
    name: 'GitHub Copilot Freelancing',
    shortDescription: 'Leverage AI coding assistants to boost freelance development productivity.',
    fullDescription: 'With AI coding tools like GitHub Copilot, freelance developers can dramatically increase their productivity and take on more projects. This approach combines AI-assisted coding with freelance platforms to build software faster. Developers report 30-50% productivity gains, allowing them to complete more projects and earn more. Ideal for web developers, mobile developers, and automation specialists.',
    category: 'Development',
    earningPotential: '$$$$$',
    rating: 4.6,
    website: 'https://github.com/features/copilot',
    logo: '',
    steps: [
      'Learn programming fundamentals thoroughly',
      'Subscribe to GitHub Copilot',
      'Build a portfolio of AI-assisted projects',
      'Join freelance platforms (Upwork, Toptal)',
      'Take on projects and deliver faster with AI',
    ],
    pros: [
      'Highest earning potential',
      'AI boosts productivity 30-50%',
      'Growing demand for developers',
      'Can work completely remotely',
      'Build valuable long-term skills',
    ],
    cons: [
      'Requires coding knowledge',
      'Initial learning curve',
      'Competitive freelance market',
      'Need to stay updated with tech trends',
    ],
    tags: ['Development', 'AI Coding', 'Freelancing', 'High Income', 'Programming'],
  },
  // ==================== NEW PLATFORMS (13-20) ====================
  {
    name: 'Synthesia',
    shortDescription: 'Create and sell professional AI-generated videos with virtual avatars.',
    fullDescription: 'Synthesia is a powerful AI video creation platform that lets you generate professional videos using AI avatars and voiceovers. No camera, microphone, or studio needed — just type your script and choose from 150+ diverse AI avatars speaking in 120+ languages. Freelancers use it to offer corporate training videos, product demos, explainer videos, and social media content as a service.',
    category: 'AI Tools',
    earningPotential: '$$$$',
    rating: 4.4,
    website: 'https://www.synthesia.io',
    logo: '',
    steps: [
      'Sign up for a Synthesia account',
      'Explore the AI avatar and template library',
      'Create sample videos to build your portfolio',
      'Offer AI video creation as a freelance service',
      'Scale by offering packages for corporate clients',
    ],
    pros: [
      'No video production equipment needed',
      'Fast turnaround — videos in minutes',
      '150+ AI avatars, 120+ languages',
      'Professional quality output',
      'High demand from corporate clients',
    ],
    cons: [
      'Monthly subscription cost ($22-67/mo)',
      'Avatar limitations for some use cases',
      'Requires good scriptwriting skills',
      'Some clients prefer real human presenters',
    ],
    tags: ['AI Video', 'Content Creation', 'Freelancing', 'Corporate', 'Avatars'],
  },
  {
    name: 'Copy.ai',
    shortDescription: 'Use AI to generate marketing copy and offer copywriting as a freelance service.',
    fullDescription: 'Copy.ai is an AI-powered copywriting tool that generates high-quality marketing content in seconds. From social media posts and ad copy to blog introductions and product descriptions, it covers virtually every copywriting need. Freelancers leverage it to dramatically increase their output, offering AI-enhanced copywriting services on platforms like Fiverr and Upwork at competitive rates.',
    category: 'Content Creation',
    earningPotential: '$$$',
    rating: 4.2,
    website: 'https://www.copy.ai',
    logo: '',
    steps: [
      'Create a free Copy.ai account',
      'Explore the 90+ content templates',
      'Practice generating different types of copy',
      'Set up freelance gigs offering AI copywriting',
      'Use Copy.ai to deliver faster and earn more',
    ],
    pros: [
      'Free tier available',
      '90+ content generation templates',
      'Increases copywriting speed 5-10x',
      'Supports multiple languages',
      'Easy to integrate into freelance workflow',
    ],
    cons: [
      'Output needs human editing and refinement',
      'Premium features require paid plan',
      'Competition from other AI copywriters',
      'Some clients may not value AI-generated copy',
    ],
    tags: ['AI Writing', 'Copywriting', 'Marketing', 'Freelancing', 'Content'],
  },
  {
    name: 'Runway ML',
    shortDescription: 'Offer AI video editing and generation services using cutting-edge tools.',
    fullDescription: 'Runway ML is a creative AI toolkit that offers video generation, image editing, background removal, and more. It\'s used by professionals in film, advertising, and social media to create stunning visual content. Freelancers can offer AI-powered video editing services — removing backgrounds, generating B-roll, applying style transfers, and creating motion graphics with minimal effort.',
    category: 'Design',
    earningPotential: '$$$$',
    rating: 4.5,
    website: 'https://runwayml.com',
    logo: '',
    steps: [
      'Sign up for Runway ML',
      'Learn the Gen-2 video generation tools',
      'Create a portfolio of AI-edited videos',
      'Offer AI video editing on freelance platforms',
      'Specialize in a niche (ads, social media, film)',
    ],
    pros: [
      'Industry-leading AI video tools',
      'Used by major film studios',
      'Fast, professional results',
      'Wide range of creative tools',
      'Growing demand for AI video editing',
    ],
    cons: [
      'Requires creative skills to maximize',
      'Subscription can be expensive ($12-76/mo)',
      'Rendering times for complex projects',
      'Learning curve for advanced features',
    ],
    tags: ['AI Video', 'Video Editing', 'Design', 'Creative', 'Film'],
  },
  {
    name: 'Descript',
    shortDescription: 'AI-powered podcast and video editing — offer editing services to creators.',
    fullDescription: 'Descript revolutionizes audio and video editing by treating media like a text document. Edit video by editing the transcript, remove filler words automatically, clone your voice, and generate studio-quality audio. Podcast editors and video editors use Descript to offer fast, affordable editing services to the 4+ million active podcasters and millions of YouTubers worldwide.',
    category: 'Content Creation',
    earningPotential: '$$$',
    rating: 4.3,
    website: 'https://www.descript.com',
    logo: '',
    steps: [
      'Download and install Descript',
      'Learn transcript-based editing workflow',
      'Create sample edits for your portfolio',
      'Market your AI-powered editing services',
      'Build recurring clients (weekly podcasts, vlogs)',
    ],
    pros: [
      'Revolutionary text-based video editing',
      'Auto-remove filler words (um, uh)',
      'AI voice cloning for corrections',
      'Fast editing — 5x faster than traditional',
      'Recurring income from weekly shows',
    ],
    cons: [
      'Free plan has limitations',
      'Requires understanding of audio/video basics',
      'AI transcription not always perfect',
      'Some clients prefer traditional editing',
    ],
    tags: ['Podcast', 'Video Editing', 'AI Audio', 'Content Creation', 'Recurring Income'],
  },
  {
    name: 'Topaz Labs',
    shortDescription: 'Offer AI photo and video enhancement services to photographers.',
    fullDescription: 'Topaz Labs provides AI-powered tools for image upscaling, noise reduction, sharpening, and video enhancement. Photographers and videographers use these tools to rescue low-quality images, upscale old photos, and enhance video footage. As a service, you can offer photo restoration, batch enhancement of real estate photos, e-commerce product image enhancement, and old video upscaling.',
    category: 'Design',
    earningPotential: '$$',
    rating: 4.0,
    website: 'https://www.topazlabs.com',
    logo: '',
    steps: [
      'Purchase Topaz Photo AI or Video AI',
      'Practice with various enhancement scenarios',
      'Offer photo enhancement on freelance platforms',
      'Target niches: real estate, e-commerce, restoration',
      'Scale with batch processing capabilities',
    ],
    pros: [
      'Industry-best AI upscaling quality',
      'One-time purchase (no subscription)',
      'Batch processing for efficiency',
      'High demand in real estate and e-commerce',
      'Easy to learn and use',
    ],
    cons: [
      'Initial software purchase cost ($99-199)',
      'Requires a powerful computer (GPU)',
      'Processing time for large batches',
      'Lower per-project rates than creative work',
    ],
    tags: ['Photo Enhancement', 'AI Upscaling', 'Design', 'Real Estate', 'E-commerce'],
  },
  {
    name: 'Murf AI',
    shortDescription: 'Generate professional AI voiceovers and offer voice services to clients.',
    fullDescription: 'Murf AI is a text-to-speech platform that generates ultra-realistic AI voiceovers in 20+ languages with 120+ voices. It\'s used for e-learning, YouTube videos, podcasts, IVR systems, and corporate presentations. Freelancers can offer AI voiceover services at lower prices than human voice actors while maintaining near-human quality, making it a lucrative AI-powered side hustle.',
    category: 'AI Tools',
    earningPotential: '$$',
    rating: 3.9,
    website: 'https://murf.ai',
    logo: '',
    steps: [
      'Create a Murf AI account',
      'Explore voice options and customize tone/pitch',
      'Create sample voiceovers for your portfolio',
      'List voiceover services on Fiverr/Upwork',
      'Deliver fast, affordable voiceover projects',
    ],
    pros: [
      'Ultra-realistic AI voices',
      '120+ voices in 20+ languages',
      'No recording equipment needed',
      'Fast delivery — minutes not hours',
      'Undercuts traditional voiceover pricing',
    ],
    cons: [
      'Monthly subscription required',
      'Cannot match top human voice actors',
      'Some clients prefer real human voices',
      'Limited customization for unique voices',
    ],
    tags: ['AI Voice', 'Voiceover', 'Text-to-Speech', 'E-learning', 'Content'],
  },
  {
    name: 'DataAnnotation.tech',
    shortDescription: 'Train AI models as a domain expert — earn $20-50/hr on specialized tasks.',
    fullDescription: 'DataAnnotation.tech connects subject matter experts with AI companies needing human feedback for model training. Tasks include evaluating AI responses, writing domain-specific prompts, coding assessments, mathematical problem-solving, and creative writing reviews. Pay rates are among the highest in the AI training space, ranging from $20-50/hr depending on expertise and task complexity.',
    category: 'Data Labeling',
    earningPotential: '$$$$',
    rating: 4.1,
    website: 'https://www.dataannotation.tech',
    logo: '',
    steps: [
      'Apply at dataannotation.tech',
      'Complete the qualification assessment in your domain',
      'Pass the onboarding process',
      'Start receiving tasks matched to your expertise',
      'Maintain quality to keep receiving high-paying tasks',
    ],
    pros: [
      'High pay rates ($20-50/hr)',
      'Intellectually engaging work',
      'Flexible scheduling',
      'Work from anywhere',
      'Growing AI industry demand',
    ],
    cons: [
      'Competitive application process',
      'Task availability fluctuates',
      'Strict quality standards',
      'Payment processing times vary',
    ],
    tags: ['AI Training', 'Data Labeling', 'Expert', 'High Pay', 'Remote'],
  },
  {
    name: 'Jasper AI',
    shortDescription: 'Generate marketing content at scale and offer AI content services.',
    fullDescription: 'Jasper AI (formerly Jarvis) is an enterprise-grade AI content platform used by marketers, agencies, and freelancers. It excels at generating long-form blog posts, ad copy, email campaigns, and social media content. With brand voice training and team collaboration features, freelancers can offer comprehensive AI-powered content marketing services to businesses of all sizes.',
    category: 'Content Creation',
    earningPotential: '$$$',
    rating: 4.2,
    website: 'https://www.jasper.ai',
    logo: '',
    steps: [
      'Sign up for Jasper AI (7-day free trial)',
      'Learn to use templates and brand voice features',
      'Create sample content for different industries',
      'Offer AI content marketing as a freelance service',
      'Build retainer clients for recurring monthly income',
    ],
    pros: [
      'Best-in-class AI content generation',
      'Brand voice customization',
      'SEO-optimized content templates',
      'Integrates with Surfer SEO',
      'Enterprise clients pay premium rates',
    ],
    cons: [
      'Expensive subscription ($49-125/mo)',
      'Output still needs human editing',
      'Competitive AI content market',
      'Some clients skeptical of AI content',
    ],
    tags: ['AI Writing', 'Content Marketing', 'SEO', 'Freelancing', 'Enterprise'],
  },
];

const seedDB = async () => {
  try {
    await connectDB();
    console.log('🗑️  Clearing existing platforms...');
    await Platform.deleteMany({});
    console.log('📦 Seeding platforms...');
    await Platform.insertMany(platforms);
    console.log(`✅ Successfully seeded ${platforms.length} platforms!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
};

seedDB();
